---
- include: dependences.yaml
  when:
    - common_only_deploy == False

- include: permissions.yaml

- include: files.yaml
  when:
    - common_only_deploy == False

- include: pip.yaml
  when:
    - common_only_deploy == False

- include: environment.yaml

- include: apps.yaml

- include: copy_files.yaml
